Added overload for error(message, {code, data}).
Prestaul/jsend pull request #6
Opened 2015-07-08 21:27 UTC by geirsagberg

Because message is always required, it would be convenient to type message directly, and pass code and/or data as part of a second argument object.

2019-06-20 21:46 UTC, Prestaul requested changes
Thanks for the suggesting and the PR. This does look like a good (and safely backwards compatible) improvement.

2019-06-20 21:46 UTC, Prestaul commented on index.js
> +				if(rest.data) json.data = rest.data;
As on lines 111 and 112 below, we really have to check for `undefined` explicitly given that `false`, `null`, zero, and the empty string are all valid values.

2019-06-21 22:36 UTC, geirsagberg commented on index.js
> +				if(rest.data) json.data = rest.data;
Done :)

2019-07-03 16:15 UTC, Prestaul commented on index.js
> +			if(rest !== undefined) {
```suggestion
			if(rest) {
```

2019-07-03 16:17 UTC, Prestaul approved these changes
Thanks again for the change and sorry it took so long to get around to looking into it.

2019-07-03 16:17 UTC, merged

2019-07-03 16:40 UTC, Prestaul commented
Landed after [minor changes](https://github.com/Prestaul/jsend/commit/6b5326aa623411bc28932051b0768c1fdf5ac8ab) from me on npm as `jsend@1.1.0`.

Thanks again!